data <- read.table("./data/household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
data1 <- subset(data,as.Date(data$Date,"%d/%m/%Y")=="2007-02-01")
data2 <- subset(data,as.Date(data$Date,"%d/%m/%Y")=="2007-02-02")
data3 <- rbind(data1,data2)
data4 <- as.numeric(data3$Global_active_power)
data5 <- as.numeric(data3$Global_reactive_power)
data6 <- strptime(paste(data3$Date,data3$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
data7 <- as.numeric(data3$Voltage)
data8 <- as.numeric(subSetData$Sub_metering_1)
data9 <- as.numeric(subSetData$Sub_metering_2)
data10 <- as.numeric(subSetData$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(data6,data4,type="l", xlab="", ylab="Global Active Power")
plot(data6,data7,type="l", xlab="datetime", ylab="Voltage")
plot(data6,data8,type="l",ylab="Energy Submetering",xlab="")
lines(data6,data9,type="l",col="red")
lines(data6,data10,type="l",col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
plot(data6,data5,type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
