data <- read.table("./data/household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
data1 <- subset(data,as.Date(data$Date,"%d/%m/%Y")=="2007-02-01")
data2 <- subset(data,as.Date(data$Date,"%d/%m/%Y")=="2007-02-02")
data3 <- rbind(data1,data2)
data4 <- strptime(paste(data3$Date,data3$Time,sep=" "), "%d/%m/%Y %H:%M:%S")
data5 <- as.numeric(subSetData$Sub_metering_1)
data6 <- as.numeric(subSetData$Sub_metering_2)
data7 <- as.numeric(subSetData$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(data4,data5,type="l",ylab="Energy Submetering",xlab="")
lines(data4,data6,type="l",col="red")
lines(data4,data7,type="l",col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()
